version: '3.8'

services:
  backend:
    container_name: solvenp_backend_staging
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=staging
      - FIREBASE_ADMIN_SDK_PATH=/app/firebase-adminsdk.json
    volumes:
      - ./backend:/app
      - ./backend/firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug
    restart: unless-stopped
    labels:
      - "environment=staging"

  frontend:
    container_name: solvenp_frontend_staging
    build:
      context: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://solvenp.com/api
    restart: unless-stopped
    labels:
      - "environment=staging"

networks:
  default:
    name: solvenp_staging_network
