version: '3.8'

services:
  backend:
    container_name: solvenp_backend_prod
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FIREBASE_ADMIN_SDK_PATH=/app/firebase-adminsdk.json
    volumes:
      - ./backend:/app
      - ./backend/firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level info
    restart: unless-stopped

  frontend:
    container_name: solvenp_frontend_prod
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: solvenp_prod_network
